language: java
jdk: oraclejdk8

before_install:
  - chmod +x mvnw

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 9ec2ebb6-a445-4fac-8d5f-69bb59b34339